package com.milesforce.mwbewb.Model;

import java.io.Serializable;

public class FeesData implements Serializable {
    /*   "id": 15,
                "cpa_ewb_id": 14,
                "can_id": "215",
                "can_name": "Karthik",
                "batch": "CPA-M7-01",
                "mobile_no": "9985814258",
                "email": "mailto:vangkartik@gmail.com",
                "Company": "HSBC",
                "prof_initial_agreed_fees": "Rs79,200.00",
                "publication_initial_fee": "Rs0.00",
                "pgda_fee_agreed": "Rs0.00",
                "prof_add_on_fees": "Rs0.00",
                "publication_add_on_fee": "Rs0.00",
                "total_fees": "Rs79,200.00",
                "received": "Rs39,600.00",
                "percent_received": "50%",
                "fees_due": "Rs39,600.00",
                "percent_due": "50%",
                "collection_status": "Default",
                "enrollment_date": "16-Nov-11",
                "payment_extended_deadline": "31-Dec-11",
                "osm_defaulter_confirmation": "Default",
                "for_ee": "",
                "Follow up Date": "15-Jan-16",
                "CM Comments": "dropped out the plan of CPA",
                "Accounts Followup date": "",
                "Accounts Comments": "",
                "Fees - Prof": "Rs79,200.00",
                "Received - Prof": "Rs39,600.00",
                "Due - Prof": "Rs39,600.00",
                "Fees - Pub": "Rs0.00",
                "Received - Pub": "Rs0.00",
                "Due - Pub": "Rs0.00",
                "Fees - PGDA": "Rs0.00",
                "Received - PGDA": "Rs0.00",
                "Due - PGDA": "Rs0.00",
                "INT REF": "No",
                "CD Received Date": "CD13389",
                "Empty": "",
                "CD Given to Can": "",
                "Video Access": "",
                "Empty again": "",
                "Lead Owner": "#REF!",
                "mobile_found": 1,
                "email_found": 0,
                "mwb_id": 16037,
                "going_to_process": 1,
                "comments": null,
                "created_at": "2019-10-09 06:57:17",
                "updated_at": "2019-10-10 10:10:34"*/
}
